### ISSUE TITLE
How to get all entries from a table table

### ISSUE THREAD

**Issue by mdsirr** [manavo/CodeIgniter-ORM#2]
I wanna get all user from user table. Is it possible ?

**Comment by manavo** [comment]
Yes, it is possible. You can call `getAll()` on your model. That should return all the entries!

**Comment by mdsirr** [comment]
Thank you. I'm using it.
I need another facility, can I set where condition ?
Like ->where("name", "mdsirdiu")

Another issue, in my project all model are named as User_model.php structure. How can I fix it. Please

**Comment by manavo** [comment]
You can set the where like this (https://github.com/manavo/CodeIgniter-ORM/blob/master/MY_Model.php#L385):

```
$users = $this->User_model->getAll(array('name' => 'mdsirdiu'));
```

Not sure what you mean by `all model are named as User_model.php structure. How can I fix it`. Don't understand where the problem is? Does that cause any problems specifically with the ORM?
